#!/bin/bash
# GitHub Branch Protection Setup Script
# This script provides the configuration needed for branch protection rules

echo "🔧 GitHub Branch Protection Setup"
echo "=================================="
echo ""

echo "📋 Required Branch Protection Rules:"
echo ""
echo "1. Main Branch Protection:"
echo "   - Require pull request reviews (1 reviewer)"
echo "   - Require status checks to pass"
echo "   - Require branches to be up to date"
echo "   - Include administrators"
echo ""

echo "2. Required Status Checks:"
echo "   - CI (ci.yml)"
echo "   - Test (test.yml)"
echo "   - Quality (quality.yml)"
echo "   - Integration (integration.yml)"
echo ""

echo "3. Dependabot Configuration:"
echo "   - Auto-merge enabled for patch updates"
echo "   - Auto-merge enabled for minor updates (with review)"
echo ""

echo "🔗 Setup Instructions:"
echo ""
echo "1. Go to GitHub repository Settings"
echo "2. Navigate to 'Branches' in the sidebar"
echo "3. Click 'Add rule' under 'Branch protection rules'"
echo "4. Set branch name pattern: 'main'"
echo "5. Enable the following options:"
echo "   ✅ Require a pull request before merging"
echo "   ✅ Require approvals (1)"
echo "   ✅ Require status checks to pass"
echo "   ✅ Require branches to be up to date before merging"
echo "   ✅ Include administrators"
echo ""

echo "6. Add these status checks:"
echo "   - CI"
echo "   - Test"
echo "   - Quality"
echo "   - Integration"
echo ""

echo "7. Repeat for 'develop' branch"
echo ""

echo "8. Go to 'Settings' > 'Security' > 'Dependabot'"
echo "9. Enable version updates"
echo ""

echo "📁 Files Created:"
echo "   ✅ .github/workflows/ci.yml - Main CI pipeline"
echo "   ✅ .github/workflows/test.yml - Multi-Python testing"
echo "   ✅ .github/workflows/quality.yml - Code quality checks"
echo "   ✅ .github/workflows/integration.yml - HA integration tests"
echo "   ✅ .github/workflows/dependency-review.yml - Security scanning"
echo "   ✅ .github/workflows/pr-validation.yml - PR validation"
echo "   ✅ .github/workflows/release.yml - Release automation"
echo "   ✅ .github/CODEOWNERS - Code ownership rules"
echo "   ✅ .github/dependabot.yml - Dependency updates"
echo ""

echo "🚀 Next Steps:"
echo "1. Push these changes to trigger initial CI run"
echo "2. Configure branch protection rules in GitHub"
echo "3. Enable Dependabot in repository settings"
echo "4. Set up repository secrets if needed (PYPI_USERNAME, PYPI_PASSWORD)"
echo ""

echo "🎯 The CI system will now:"
echo "   - Run tests on every PR and push"
echo "   - Enforce code quality standards"
echo "   - Prevent merging without passing checks"
echo "   - Automatically update dependencies"
echo "   - Comment on PRs with test results"
