name: Typing

on:
  push:
    branches: [ master, develop ]
    paths: [
      ".github/workflows/check-type.yml", ".pre-commit-config.yaml",
      "custom_components/**.py", "tests/**.py",
    ]
  pull_request:
    branches: [ master, develop ]
    paths: [
      ".github/workflows/check-type.yml", ".pre-commit-config.yaml",
      "custom_components/**.py", "tests/**.py",
    ]
  schedule:
    - cron: "0 6 * * 1"  # Weekly on Monday at 6 AM UTC
  workflow_dispatch:

jobs:
  type:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check with mypy
        run: mypy

      - run: echo "🍏 This job's status is ${{ job.status }}."
