name: Integration

on:
  push:
    branches: [ main, develop ]
    paths: [
      ".github/workflows/check-integration.yml", "requirements*.txt",
      "custom_components/**.py", "tests/**",
    ]
  pull_request:
    branches: [ main, develop ]
    paths: [
      ".github/workflows/check-integration.yml", "requirements*.txt",
      "custom_components/**.py", "tests/**",
    ]
  schedule:
    - cron: "0 6 * * 1"  # Weekly on Monday at 6 AM UTC
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Validate integration structure
        run: |
          # Check if integration can be imported
          python -c "import custom_components.ramses_extras"
          echo "✅ Integration imports successfully"

      - name: Validate manifest
        run: |
          python -c "
          import json
          with open('custom_components/ramses_extras/manifest.json') as f:
              manifest = json.load(f)
              print(f'✅ Integration: {manifest[\"name\"]} v{manifest[\"version\"]}')
              print(f'✅ Domain: {manifest[\"domain\"]}')
          "

      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: Validate configuration
        run: |
          # Test configuration validation
          python -c "
          import custom_components.ramses_extras as ramses_extras
          print('✅ Integration imports successfully')
          print(f'DOMAIN: {ramses_extras.DOMAIN}')
          print(f'Available features: {len(ramses_extras.AVAILABLE_FEATURES)}')
          "
