name: Linting

on:
  push:
    branches: ['master', 'develop']
    paths:
      [
        '.github/workflows/check-lint.yml',
        'custom_components/**',
        'tests/**',
        'pyproject.toml',
        'package.json',
        'package-lock.json',
      ]

  pull_request:
    branches: ['master', 'develop']
    paths:
      [
        '.github/workflows/check-lint.yml',
        'custom_components/**',
        'tests/**',
        'pyproject.toml',
        'package.json',
        'package-lock.json',
      ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run pre-commit
        run: pre-commit run --all-files

      - run: echo "🍏 This job's status is ${{ job.status }}."
