name: CI

on:
  push:
    branches: [ master, develop ]
    paths: [
      ".github/workflows/ci.yml", "requirements*.txt",
      "custom_components/**.py", "tests/**",
    ]
  pull_request:
    branches: [ master, develop ]
    paths: [
      ".github/workflows/ci.yml", "requirements*.txt",
      "custom_components/**.py", "tests/**",
    ]
  schedule:
    - cron: "0 6 * * 1"  # Weekly on Monday at 6 AM UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Test with pytest
        env:
          PYTEST_ADDOPTS: "--color=yes"
        run: pytest -v

      - run: echo "🍏 This job's status is ${{ job.status }}."

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy

      - name: Check with ruff
        run: ruff check --output-format=github .

      - name: Check with mypy
        run: mypy

      - run: echo "🍏 This job's status is ${{ job.status }}."
