name: Dependency Update

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.py'
      - '.github/workflows/**'

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-deps-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-deps-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check for outdated dependencies
      run: |
        pip install pip-tools
        pip-compile --dry-run requirements.txt

    - name: Run tests with new dependencies
      run: |
        pip install -e .
        pytest tests/ -v --tb=short
