name: Integration

on:
  push:
    branches: [ main, develop ]
    paths: [
      ".github/workflows/integration.yml", "requirements*.txt",
      "custom_components/**.py", "tests/**",
    ]
  pull_request:
    branches: [ main, develop ]
    paths: [
      ".github/workflows/integration.yml", "requirements*.txt",
      "custom_components/**.py", "tests/**",
    ]
  schedule:
    - cron: "0 6 * * 1"  # Weekly on Monday at 6 AM UTC
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest

    services:
      homeassistant:
        image: homeassistant/home-assistant:2025.10.1
        ports:
          - 8123:8123
        volumes:
          - ${{ github.workspace }}/custom_components:/config/custom_components
        options: --name homeassistant-integration

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Home Assistant
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:8123/manifest.json; do sleep 1; done'

    - name: Install integration
      run: |
        cp -r custom_components/ramses_extras /config/custom_components/

    - name: Check integration loading
      run: |
        # Check if integration appears in HA logs
        docker logs homeassistant-integration | grep -i "ramses_extras" || echo "Integration not found in logs"

    - name: Validate configuration
      run: |
        # Test configuration validation
        python -c "
        import custom_components.ramses_extras as ramses_extras
        print('Integration imports successfully')
        print(f'DOMAIN: {ramses_extras.DOMAIN}')
        print(f'Available features: {len(ramses_extras.AVAILABLE_FEATURES)}')
        "
