name: Quality

on:
  push:
    branches: [ main, develop ]
    paths: [
      ".github/workflows/quality.yml", ".pre-commit-config.yaml",
      "custom_components/**.py", "tests/**",
    ]
  pull_request:
    branches: [ main, develop ]
    paths: [
      ".github/workflows/quality.yml", ".pre-commit-config.yaml",
      "custom_components/**.py", "tests/**",
    ]
  schedule:
    - cron: "0 6 * * 1"  # Weekly on Monday at 6 AM UTC
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-quality-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-quality-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pre-commit hooks
      run: |
        pre-commit run -a

    - name: Check code formatting and linting
      run: |
        ruff format --check .
        ruff check .

    - name: Run mypy type checking
      run: |
        mypy custom_components/ tests/

    - name: Security check
      run: |
        pip install safety
        safety check
