name: Validate Workflows

on:
  push:
    branches: [ main, develop ]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '.github/workflows/**'

jobs:
  validate-workflows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate GitHub Actions workflows
      uses: github/super-linter/slim@v7
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_GITHUB_ACTIONS: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check workflow syntax
      run: |
        for file in .github/workflows/*.yml; do
          echo "Checking $file..."
          python -c "
          import yaml
          with open('$file') as f:
              data = yaml.safe_load(f)
              print(f'✅ $file is valid YAML')
              print(f'   - Triggers: {list(data.get(\"on\", {}).keys())}')
              print(f'   - Jobs: {len(data.get(\"jobs\", {}))}')
          "
        done
